language: node_js
node_js:
  - "10.9"
cache:
  directories:
    - "node_modules"
before_script:
  - 'echo $TRAVIS_BRANCH'
  - 'echo $TRAVIS_PULL_REQUEST'
script:

#  - npm run lint
#  - npm run test:ci:all:no-record
  - npm run build:prod

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: hapkido-admin-site
  region: ap-southeast-2
  local-dir: www
  skip_cleanup: true
