language: node_js
node_js:
  - 10.8
dist: trusty
sudo: required
addons:
  chrome: stable # have Travis install Chrome stable.
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - npm install
cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache
defaults: &defaults
  script:
    - npm run lint
    - npm run test-ci
    -
    #   ## print all Travis environment variables for debugging
    - $(npm bin)/print-env TRAVIS
    - npm start -- --silent &
    - npm run cy:run -- --record --parallel --group $STAGE_NAME
    # after all tests finish running we need
    # to kill all background jobs (like "npm start &")
    - kill $(jobs -p) || true


jobs:
  include:
    # we have multiple jobs to execute using just a single stage
    # but we can pass group name via environment variable to Cypress test runner
    - stage: e2e-test
    env:
      - STAGE_NAME=1x-electron
    <<: *defaults
      # run tests in parallel by including several test jobs with same name variable
      - stage: e2e-test
        env:
          - STAGE_NAME=4x-electron
        <<: *defaults
      - stage: e2e-test
        env:
          - STAGE_NAME=4x-electron
        <<: *defaults
      - stage: e2e-test
        env:
          - STAGE_NAME=4x-electron
        <<: *defaults
      - stage: e2e-test
        env:
          - STAGE_NAME=4x-electron
        <<: *defaults