language: node_js
node_js:
  - "12.0"
cache:
  directories:
    - "node_modules"
before_script:
  - 'echo $TRAVIS_BRANCH'
  - 'echo $TRAVIS_PULL_REQUEST'
jobs:
  include:
    - stage: tests
      script: "npm run lint && npm run test:ci"
    - stage: deploy to staging
      if: branch = staging
      script: "npm run build:staging"
      deploy:
        on: staging
        provider: s3
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        bucket: hapkido-admin-staging
        region: ap-southeast-2
        local-dir: www
        skip_cleanup: true
    - stage: deploy to prod
      if: branch = prod
      script: "npm run build:prod"
      deploy:
        on: prod
        provider: s3
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        bucket: admin.happkido.com.au
        region: ap-southeast-2
        local-dir: www
        skip_cleanup: true
