language: node_js
node_js:
  - "10.8"
cache:
  directories:
    - "node_modules"
before_script:
  - 'echo $TRAVIS_BRANCH'
  - 'echo $TRAVIS_PULL_REQUEST'
script:
  - npm run lint
  - npm run test
  - npm run cypress:ci